import type { Metadata } from "next";
import { Aldrich, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./(components)/Navbar";
import Footer from "./(section)/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"], // Customize weights as needed
});

const aldrich = Aldrich({
  subsets: ["latin"], // Adjust as needed
  weight: "400", // Specify the weight if needed
});

export const metadata: Metadata = {
  title: "Staging | Platform of Quality",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
